import type { Metadata } from "next";
import Link from "next/link";
import { Icon } from "@/components/icons";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = { title: "Nossas lojas", description: "Encontre a unidade Farmácia Poupe Mais mais próxima." };
const stores = [{ name: "Centro", address: "Rua das Flores, 120", hours: "Todos os dias • 8h às 22h", features: "Retirada em 30 min • Serviços farmacêuticos" }, { name: "Mariluz", address: "Av. Beira-Mar, 845", hours: "Seg a sáb • 8h às 21h", features: "Retirada • Entrega local" }, { name: "Imbé Norte", address: "Av. Paraguassú, 2200", hours: "Todos os dias • 9h às 22h", features: "Retirada • Sala de atendimento" }];
export default function StoresPage() { return <><SiteHeader /><main className="inner-main"><section className="page-hero"><div className="page-shell"><div className="breadcrumbs"><Link href="/">Início</Link><span>/</span><span>Lojas</span></div><span className="eyebrow">Onde você estiver</span><h1>Uma Poupe Mais por perto.</h1><p>Confira horários, serviços e opções de retirada. Endereços abaixo são demonstrativos e devem ser confirmados antes da publicação comercial.</p></div></section><div className="page-shell inner-content stores-layout"><div className="store-search"><Icon name="search" /><div><strong>Qual loja fica mais perto?</strong><p>Busque por cidade, bairro ou CEP.</p></div><input aria-label="Cidade, bairro ou CEP" placeholder="Ex.: Imbé ou 95625-000" /><button className="button button-primary">Buscar</button></div><div className="store-grid">{stores.map((store) => <article key={store.name}><span className="store-pin"><Icon name="store" size={27} /></span><div><small>Farmácia Poupe Mais</small><h2>{store.name}</h2><p>{store.address}</p><dl><div><dt><Icon name="clock" size={16} /> Horário</dt><dd>{store.hours}</dd></div><div><dt><Icon name="care" size={16} /> Disponível</dt><dd>{store.features}</dd></div></dl><div className="store-actions"><button>Ver no mapa</button><Link href="/catalogo">Comprar para retirar</Link></div></div></article>)}</div></div></main><SiteFooter /></>; }
