import type { Metadata } from "next";
import Link from "next/link";
import { Icon } from "@/components/icons";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = { title: "Serviços de saúde", description: "Serviços farmacêuticos com atendimento acolhedor e agendamento simples." };
const services = [{ icon: "heart", name: "Aferição de pressão", time: "15 min", text: "Medição e registro com orientação sobre o resultado." }, { icon: "drop", name: "Teste de glicemia", time: "15 min", text: "Teste capilar e orientação farmacêutica." }, { icon: "shield", name: "Revisão de medicamentos", time: "30 min", text: "Conversa reservada para organizar o uso correto." }, { icon: "thermo", name: "Acompanhamento de saúde", time: "20 min", text: "Registro periódico de indicadores definidos com você." }];
export default function ServicesPage() { return <><SiteHeader /><main className="inner-main"><section className="page-hero"><div className="page-shell"><div className="breadcrumbs"><Link href="/">Início</Link><span>/</span><span>Serviços</span></div><span className="eyebrow">Cuidado além do balcão</span><h1>Serviços de saúde perto de você.</h1><p>Atendimentos realizados por equipe habilitada, em ambiente reservado e com informação clara.</p></div></section><div className="page-shell inner-content"><div className="services-grid">{services.map((service) => <article key={service.name}><span><Icon name={service.icon} size={31} /></span><small>{service.time}</small><h2>{service.name}</h2><p>{service.text}</p><button className="button button-ghost">Agendar atendimento</button></article>)}</div><section className="service-note"><Icon name="care" size={42} /><div><h2>Precisa falar com um farmacêutico?</h2><p>Para sintomas intensos, persistentes ou situações de urgência, procure um serviço de saúde. Nossos serviços não substituem consulta médica.</p></div></section></div></main><SiteFooter /></>; }
